### ISSUE TITLE
Responsibility completion (main home page, responsibility show page(?)

### ISSUE THREAD

**Issue by daseyun** [kriti-g/cs4550-final-project#25]
Case 1: resp.completions < chore.rotation or chore.rotation = 0 (i.e. it's not time for the chore to rotate yet)
Details: 
- update responsibilities.completions + 1 
- update deadline . look at linked chore.frequency + current deadline. 

Case 2: resp.completions = chore.rotation (it's time for the chore to rotate)
Details: 
- Delete current responsibility
- Jason.parse the group.rotation_order
- Find previous user id ind
- inc ind by one, lookup the user at the new id
- Assign responsibility for this chore to new user
- (where new deadline = completion time + chore.frequency(days))

**Comment by daseyun** [comment]
sync completions for multiple users.

**Comment by kriti-g** [comment]
completion cases done on server side. doesn't include syncing yet. will need to test first before adding further functionality
